### ISSUE TITLE
TypeError: 'Response' object is not subscriptable

### ISSUE THREAD

**Issue by magick93** [fortinet-solutions-cse/fortiosapi#56]
Hello

I'm not sure if this is the correct repo for such an issue - apologies if I should post this somewhere else.

I'm trying to run the following ansible playbook, using Ansible AWX, but am getting the below error:

### Versions

ansible-playbook 2.9.4
python 3.6.8

### Ansible Playbook
```
---
- name: Sync ports
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
   host: "xx.xx.xx.xx"
   username: "xxxx"
   password: "xxxxx"
   vdom: "test_vdom"
   ssl_verify: "False"

  tasks:



    - name: Configure custom services.
      fortios_firewall_service_custom:
        host:  "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom:  "{{ vdom }}"
        https: "false"
        ssl_verify: "False"
  #      state: "present"
        firewall_service_custom:
            category: "test_cat"
            comment: "testing"
            name: "testing_tcp.10000"
            visibility: "enable"
            state: present
   #         ssl_verify: false
```

### Error

```
    "module_stderr": "in formatresponse res.content does not exist, should not occur\nTraceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1580769097.8021286-118964279067587/AnsiballZ_fortios_firewall_service_custom.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1580769097.8021286-118964279067587/AnsiballZ_fortios_firewall_service_custom.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1580769097.8021286-118964279067587/AnsiballZ_fortios_firewall_service_custom.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.fortios.fortios_firewall_service_custom', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_firewall_service_custom_payload_doutnw1b/ansible_fortios_firewall_service_custom_payload.zip/ansible/modules/network/fortios/fortios_firewall_service_custom.py\", line 566, in <module>\n  File \"/tmp/ansible_fortios_firewall_service_custom_payload_doutnw1b/ansible_fortios_firewall_service_custom_payload.zip/ansible/modules/network/fortios/fortios_firewall_service_custom.py\", line 555, in main\n  File \"/tmp/ansible_fortios_firewall_service_custom_payload_doutnw1b/ansible_fortios_firewall_service_custom_payload.zip/ansible/modules/network/fortios/fortios_firewall_service_custom.py\", line 391, in login\n  File \"/opt/custom-venvs/infrastructure/lib/python3.6/site-packages/fortiosapi/fortiosapi.py\", line 181, in login\n    self._fortiversion = resp_lic['version']\nTypeError: 'Response' object is not subscriptable\n",
```
