### ISSUE TITLE
Modification of the 'password' field of system.admin is forbidden

### ISSUE THREAD

**Issue by cbachert** [fortinet-solutions-cse/fortiosapi#61]
Trying to update the password of an existing system admin on a FortiGate VM64-KVM v6.2.2 fails with error
> Modification of the 'password' field of system.admin is forbidden.

See full log output below. It was attempted to apply the config via the ansible fortios_system_admin module, see as well the relevant excerpt of the play below. This looks like an issue with fortiosapi, but let me know if this should be rather handled by the ansible module.

```
[httpsd 1582 - 1585763448     info] child_main[5142] -- New PUT request for "/api/v2/cmdb/system/admin/SNMP_DUMMY" from "10.123.42.1:12400"
[httpsd 1582 - 1585763448     info] child_main[5143] -- User-Agent: "python-requests/2.23.0"
[httpsd 1582 - 1585763448     info] ap_invoke_handler[572] -- Handler "api_cmdb_v2-handler" assigned to request
[httpsd 1582 - 1585763448     info] aps_init_process_vdom[1262] -- initialized process vdom to 'root' (cookie='(null)')
[httpsd 1582 - 1585763448     info] api_store_parameter[239] -- add API parameter 'vdom' (type=string)
[httpsd 1582 - 1585763448     info] api_store_parameter[239] -- add API parameter 'accprofile' (type=string)
[httpsd 1582 - 1585763448     info] api_store_parameter[239] -- add API parameter 'name' (type=string)
[httpsd 1582 - 1585763448     info] api_store_parameter[239] -- add API parameter 'password' (type=string)
[httpsd 1582 - 1585763448     info] api_store_parameter[239] -- add API parameter 'trusthost1' (type=string)
[httpsd 1582 - 1585763448     info] handle_cli_req_v2_vdom[2123] -- new CMDB API request (vdom='root',user='admin')
[httpsd 1582 - 1585763448     info] api_cmdb_request_init_by_path[1509] -- new CMDB query (path='system',name='admin')
[httpsd 1582 - 1585763448     info] api_cmdb_request_init_by_path[1538] -- querying CMDB entry (mkey='SNMP_DUMMY')
[httpsd 1582 - 1585763448     info] _api_cmdb_v2_config[1180] -- editing CLI object (append=0, auto_key=0, path=system, name=admin, mkey=SNMP_DUMMY, flags=0)
[httpsd 1582 - 1585763448    error] _api_cmdb_v2_config[1191] -- Modification of the 'password' field of system.admin is forbidden.
[httpsd 1582 - 1585763448  warning] api_return_http_result[702] -- API error 403 raised
[httpsd 1582 - 1585763448     info] child_main[5212] -- Completed PUT request for "/api/v2/cmdb/system/admin/SNMP_DUMMY"
```
```
- name: Create dummy admin accounts to allow SNMP access via trusted hosts
  delegate_to: localhost
  fortios_system_admin:
    host: "{{ ansible_host }}"
    username: "{{ FORTIOS_USER }}"
    password: "{{ FORTIOS_PASS }}"
    vdom: "root"
    https: "{{ FORTIOS_HTTPS }}"
    ssl_verify: "{{ FORTIOS_SSL_VERIFY }}"
    state: "present"
    system_admin:
      name: "{{ 'SNMP_DUMMY }}"
      accprofile: "admin_no_access"
      trusthost1: "{{ item + ' 255.255.255.255' }}"
      password: "test"
```
